title: lonelywriter
description: Just concentrate on writing. This is a theme without any extra frills and fancy things. Get the theme <a href="https://github.com/lingxz/lonelywriter" target="_blank">here</a>.
permalink: /blog/:title/
tagline: a writing blog
url: "https://theconfused.me" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "/lonelywriter" # the subpath of your site, e.g. "/blog" leave blank if no subpath

# Conversion
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

color-theme: light
